/*
 * Niche taxonomy for market signals. GENERATED mechanically from the JSON block in
 * `invai-docs/product/market-niches.md` (PM-owned; read-only here). Do not hand-edit: change the
 * doc, then regenerate. Keys are stable ids and are never reused.
 */

export type Niche = {
  key: string;
  family: string;
  labelEn: string;
  labelEs: string;
  /** 3-5 canonical US-English buyer phrases; the only strings ever sent to a demand source. */
  queries: readonly string[];
  /** Lowercase ASCII stems matched against a design's tags and name tokens. */
  stems: readonly string[];
  /** Seasonal prior (1..12); empty for evergreen niches. */
  peakMonths: readonly number[];
};

export const NICHES: readonly Niche[] = [
  {
    key: "teacher",
    family: "Work and roles",
    labelEn: "Teachers",
    labelEs: "Maestros",
    queries: [
      "teacher shirt",
      "funny teacher t-shirt",
      "teacher appreciation shirt",
      "back to school teacher shirt",
      "teacher team shirts",
    ],
    stems: ["teach", "educat", "classroom", "maestr", "profesor", "docent"],
    peakMonths: [5, 8],
  },
  {
    key: "nurse",
    family: "Work and roles",
    labelEn: "Nurses",
    labelEs: "Enfermería",
    queries: [
      "nurse shirt",
      "funny nurse t-shirt",
      "nurses week shirt",
      "er nurse shirt",
      "nursing student shirt",
    ],
    stems: ["nurse", "nursing", "rn", "lpn", "cna", "enfermer"],
    peakMonths: [5],
  },
  {
    key: "doctor",
    family: "Work and roles",
    labelEn: "Doctors",
    labelEs: "Médicos",
    queries: [
      "doctor shirt",
      "funny doctor t-shirt",
      "medical student shirt",
      "physician gift shirt",
    ],
    stems: ["doctor", "physician", "medic", "surgeon", "cirujan", "pediatr"],
    peakMonths: [],
  },
  {
    key: "firefighter",
    family: "Work and roles",
    labelEn: "Firefighters",
    labelEs: "Bomberos",
    queries: [
      "firefighter shirt",
      "firefighter wife shirt",
      "volunteer firefighter t-shirt",
      "fire department shirt",
    ],
    stems: ["firefight", "fireman", "firemen", "firehouse", "bomber"],
    peakMonths: [],
  },
  {
    key: "police",
    family: "Work and roles",
    labelEn: "Police",
    labelEs: "Policía",
    queries: [
      "police officer shirt",
      "police wife shirt",
      "law enforcement t-shirt",
      "sheriff deputy shirt",
    ],
    stems: ["polic", "sheriff", "deputy", "cop", "enforcement", "patrol"],
    peakMonths: [],
  },
  {
    key: "military",
    family: "Work and roles",
    labelEn: "Military",
    labelEs: "Militares",
    queries: [
      "military shirt",
      "proud military family shirt",
      "military mom shirt",
      "deployment shirt",
      "support our troops shirt",
    ],
    stems: ["militar", "soldier", "soldad", "troop", "deploy", "milspouse"],
    peakMonths: [],
  },
  {
    key: "veteran",
    family: "Work and roles",
    labelEn: "Veterans",
    labelEs: "Veteranos",
    queries: ["veteran shirt", "proud veteran t-shirt", "veterans day shirt", "veteran dad shirt"],
    stems: ["veteran", "dd214", "combat", "valor"],
    peakMonths: [11],
  },
  {
    key: "trucker",
    family: "Work and roles",
    labelEn: "Truck drivers",
    labelEs: "Traileros",
    queries: ["trucker shirt", "funny trucker t-shirt", "truck driver shirt", "cdl driver shirt"],
    stems: ["trucker", "trucking", "cdl", "trailer", "camioner"],
    peakMonths: [],
  },
  {
    key: "mechanic",
    family: "Work and roles",
    labelEn: "Mechanics",
    labelEs: "Mecánicos",
    queries: ["mechanic shirt", "funny mechanic t-shirt", "diesel mechanic shirt", "car guy shirt"],
    stems: ["mechanic", "mecanic", "wrench", "garage", "diesel", "automotiv"],
    peakMonths: [],
  },
  {
    key: "farmer",
    family: "Work and roles",
    labelEn: "Farmers and ranchers",
    labelEs: "Campo y rancho",
    queries: ["farmer shirt", "farm life t-shirt", "funny farmer shirt", "tractor shirt"],
    stems: ["farm", "tractor", "ranch", "granj", "agricult", "campesin", "cattle", "barn"],
    peakMonths: [],
  },
  {
    key: "construction",
    family: "Work and roles",
    labelEn: "Construction and trades",
    labelEs: "Construcción y oficios",
    queries: [
      "construction worker shirt",
      "funny construction t-shirt",
      "electrician shirt",
      "welder shirt",
      "lineman shirt",
    ],
    stems: [
      "construc",
      "builder",
      "carpent",
      "electrician",
      "weld",
      "lineman",
      "plumb",
      "albanil",
      "ironwork",
    ],
    peakMonths: [],
  },
  {
    key: "chef",
    family: "Work and roles",
    labelEn: "Chefs and cooks",
    labelEs: "Chefs y cocineros",
    queries: [
      "chef shirt",
      "funny chef t-shirt",
      "cooking shirt",
      "line cook shirt",
      "baker shirt",
    ],
    stems: ["chef", "cook", "cocin", "culinar", "kitchen", "baker", "panader", "bbq", "grill"],
    peakMonths: [],
  },
  {
    key: "hairstylist",
    family: "Work and roles",
    labelEn: "Hairstylists and barbers",
    labelEs: "Estilistas y barberos",
    queries: [
      "hairstylist shirt",
      "funny hair stylist t-shirt",
      "cosmetologist shirt",
      "barber shirt",
      "salon shirt",
    ],
    stems: [
      "hairstyl",
      "hairdress",
      "stylist",
      "cosmetolog",
      "barber",
      "salon",
      "estilist",
      "peluquer",
    ],
    peakMonths: [],
  },
  {
    key: "coach",
    family: "Work and roles",
    labelEn: "Sports coaches",
    labelEs: "Entrenadores",
    queries: ["sports coach shirt", "coach gift t-shirt", "funny coach shirt", "team coach shirt"],
    stems: ["coach", "entrenador", "trainer", "whistle"],
    peakMonths: [],
  },
  {
    key: "mom",
    family: "Family",
    labelEn: "Moms",
    labelEs: "Mamás",
    queries: [
      "mom shirt",
      "funny mom t-shirt",
      "mom life shirt",
      "best mom ever shirt",
      "boy mom shirt",
    ],
    stems: ["mom", "mommy", "mama", "momma", "mother", "madre", "mami", "mum"],
    peakMonths: [5],
  },
  {
    key: "dad",
    family: "Family",
    labelEn: "Dads",
    labelEs: "Papás",
    queries: [
      "dad shirt",
      "funny dad t-shirt",
      "dad joke shirt",
      "best dad ever shirt",
      "girl dad shirt",
    ],
    stems: ["dad", "daddy", "father", "papa", "padre", "papi", "pops"],
    peakMonths: [6],
  },
  {
    key: "grandma",
    family: "Family",
    labelEn: "Grandmas",
    labelEs: "Abuelas",
    queries: ["grandma shirt", "funny grandma t-shirt", "nana shirt", "grandma gift shirt"],
    stems: ["grandma", "grandmother", "granny", "nana", "gigi", "mimi", "abuela", "abuelita"],
    peakMonths: [5, 9],
  },
  {
    key: "grandpa",
    family: "Family",
    labelEn: "Grandpas",
    labelEs: "Abuelos",
    queries: ["grandpa shirt", "funny grandpa t-shirt", "papaw shirt", "grandpa gift shirt"],
    stems: ["grandpa", "grandfather", "granddad", "papaw", "pawpaw", "abuelo", "abuelito"],
    peakMonths: [6, 9],
  },
  {
    key: "dog-mom",
    family: "Family",
    labelEn: "Dog moms",
    labelEs: "Mamás perrunas",
    queries: ["dog mom shirt", "funny dog mom t-shirt", "dog mama shirt", "fur mama shirt"],
    stems: ["dogmom", "dog", "pup", "perr", "fur", "mom", "mama", "momma", "mami"],
    peakMonths: [],
  },
  {
    key: "dog-dad",
    family: "Family",
    labelEn: "Dog dads",
    labelEs: "Papás perrunos",
    queries: ["dog dad shirt", "funny dog dad t-shirt", "dog daddy shirt", "dog father shirt"],
    stems: ["dogdad", "dog", "pup", "perr", "fur", "dad", "daddy", "papa", "papi"],
    peakMonths: [],
  },
  {
    key: "cat-mom",
    family: "Family",
    labelEn: "Cat moms",
    labelEs: "Mamás gatunas",
    queries: ["cat mom shirt", "funny cat mom t-shirt", "cat mama shirt", "cat lady shirt"],
    stems: ["catmom", "cat", "cats", "kitt", "gata", "gatit", "michi", "meow", "mom", "mama"],
    peakMonths: [],
  },
  {
    key: "new-baby",
    family: "Family",
    labelEn: "New baby",
    labelEs: "Bebé en camino",
    queries: [
      "pregnancy announcement shirt",
      "new baby shirt",
      "baby shower shirt",
      "big sister shirt",
    ],
    stems: ["baby", "bebe", "newborn", "pregnan", "embaraz", "expecting", "announce"],
    peakMonths: [],
  },
  {
    key: "family-reunion",
    family: "Family",
    labelEn: "Family reunions",
    labelEs: "Reuniones familiares",
    queries: [
      "family reunion shirt",
      "family reunion t-shirts",
      "personalized family reunion shirts",
    ],
    stems: ["reunion", "family", "familia", "cousin", "primos", "primas", "gathering"],
    peakMonths: [6, 7],
  },
  {
    key: "matching-family",
    family: "Family",
    labelEn: "Matching family shirts",
    labelEs: "Playeras iguales para la familia",
    queries: [
      "matching family shirts",
      "family vacation shirts",
      "matching christmas family shirts",
      "mom and daughter matching shirts",
    ],
    stems: ["matching", "family", "familia", "iguales", "twinning"],
    peakMonths: [],
  },
  {
    key: "christmas",
    family: "Holidays",
    labelEn: "Christmas",
    labelEs: "Navidad",
    queries: [
      "christmas shirt",
      "funny christmas t-shirt",
      "christmas family shirts",
      "merry christmas shirt",
      "christmas tree shirt",
    ],
    stems: ["christmas", "xmas", "navid", "santa", "reindeer", "snowm", "jingle", "noel"],
    peakMonths: [11, 12],
  },
  {
    key: "halloween",
    family: "Holidays",
    labelEn: "Halloween",
    labelEs: "Halloween",
    queries: [
      "halloween shirt",
      "funny halloween t-shirt",
      "halloween costume shirt",
      "spooky season shirt",
      "ghost shirt",
    ],
    stems: ["halloween", "spook", "ghost", "pumpkin", "witch", "bruj", "calabaz", "fantasm"],
    peakMonths: [9, 10],
  },
  {
    key: "thanksgiving",
    family: "Holidays",
    labelEn: "Thanksgiving",
    labelEs: "Día de Acción de Gracias",
    queries: [
      "thanksgiving shirt",
      "funny thanksgiving t-shirt",
      "thankful shirt",
      "turkey day shirt",
    ],
    stems: ["thanksgiving", "thankful", "grateful", "gratitud", "turkey", "pavo", "gracias"],
    peakMonths: [11],
  },
  {
    key: "valentines",
    family: "Holidays",
    labelEn: "Valentine's Day",
    labelEs: "San Valentín",
    queries: [
      "valentines day shirt",
      "funny valentine t-shirt",
      "valentine shirt for women",
      "heart valentine shirt",
    ],
    stems: ["valentin", "cupid", "heart", "corazon", "amor", "xoxo"],
    peakMonths: [1, 2],
  },
  {
    key: "st-patricks",
    family: "Holidays",
    labelEn: "St. Patrick's Day",
    labelEs: "Día de San Patricio",
    queries: [
      "st patricks day shirt",
      "funny st patricks t-shirt",
      "irish shirt",
      "lucky shirt",
      "shamrock shirt",
    ],
    stems: ["patrick", "patricio", "shamrock", "irish", "lucky", "clover", "trebol", "leprechaun"],
    peakMonths: [2, 3],
  },
  {
    key: "easter",
    family: "Holidays",
    labelEn: "Easter",
    labelEs: "Pascua",
    queries: ["easter shirt", "easter bunny shirt", "kids easter t-shirt", "he is risen shirt"],
    stems: ["easter", "bunny", "pascua", "conejit", "egg", "risen", "resurrec"],
    peakMonths: [3, 4],
  },
  {
    key: "4th-of-july",
    family: "Holidays",
    labelEn: "4th of July",
    labelEs: "4 de julio",
    queries: [
      "4th of july shirt",
      "fourth of july t-shirt",
      "patriotic shirt",
      "usa flag shirt",
      "independence day shirt",
    ],
    stems: ["july", "julio", "4th", "fourth", "patriot", "america", "usa", "independence"],
    peakMonths: [6, 7],
  },
  {
    key: "mothers-day",
    family: "Holidays",
    labelEn: "Mother's Day",
    labelEs: "Día de las Madres",
    queries: ["mothers day shirt", "mothers day gift t-shirt", "happy mothers day shirt"],
    stems: ["mothersday", "mother", "madre", "mom", "mama", "mami"],
    peakMonths: [4, 5],
  },
  {
    key: "fathers-day",
    family: "Holidays",
    labelEn: "Father's Day",
    labelEs: "Día del Padre",
    queries: ["fathers day shirt", "fathers day gift t-shirt", "happy fathers day shirt"],
    stems: ["fathersday", "father", "padre", "dad", "papa", "papi"],
    peakMonths: [5, 6],
  },
  {
    key: "new-year",
    family: "Holidays",
    labelEn: "New Year",
    labelEs: "Año Nuevo",
    queries: ["new years eve shirt", "happy new year shirt", "new year party shirt"],
    stems: ["newyear", "nye", "countdown", "resolution", "midnight", "cheers"],
    peakMonths: [12],
  },
  {
    key: "cinco-de-mayo",
    family: "Holidays",
    labelEn: "Cinco de Mayo",
    labelEs: "Cinco de Mayo",
    queries: [
      "cinco de mayo shirt",
      "funny cinco de mayo t-shirt",
      "cinco de mayo party shirt",
      "fiesta shirt",
    ],
    stems: ["cinco", "mayo", "fiesta", "pinata", "margarit", "mexic"],
    peakMonths: [4, 5],
  },
  {
    key: "dia-de-muertos",
    family: "Holidays",
    labelEn: "Day of the Dead",
    labelEs: "Día de Muertos",
    queries: [
      "day of the dead shirt",
      "dia de los muertos shirt",
      "sugar skull shirt",
      "calavera shirt",
    ],
    stems: [
      "muerto",
      "calaver",
      "catrin",
      "sugarskull",
      "ofrenda",
      "cempasuchil",
      "marigold",
      "skull",
    ],
    peakMonths: [10],
  },
  {
    key: "hanukkah",
    family: "Holidays",
    labelEn: "Hanukkah",
    labelEs: "Janucá",
    queries: ["hanukkah shirt", "funny hanukkah t-shirt", "chanukah shirt", "menorah shirt"],
    stems: ["hanuk", "chanuk", "januc", "menorah", "dreidel", "latke"],
    peakMonths: [11, 12],
  },
  {
    key: "birthday",
    family: "Events",
    labelEn: "Birthdays",
    labelEs: "Cumpleaños",
    queries: [
      "birthday shirt",
      "birthday girl shirt",
      "birthday boy shirt",
      "funny birthday t-shirt",
      "50th birthday shirt",
    ],
    stems: ["birthday", "bday", "cumple", "turning", "cake"],
    peakMonths: [],
  },
  {
    key: "birthday-squad",
    family: "Events",
    labelEn: "Birthday group shirts",
    labelEs: "Playeras de grupo para cumpleaños",
    queries: [
      "birthday crew shirts",
      "matching birthday shirts",
      "birthday party group shirts",
      "birthday squad shirt",
    ],
    stems: ["squad", "crew", "birthday", "bday", "cumple"],
    peakMonths: [],
  },
  {
    key: "bachelorette",
    family: "Events",
    labelEn: "Bachelorette parties",
    labelEs: "Despedidas de soltera",
    queries: [
      "bachelorette party shirts",
      "bachelorette shirt",
      "bachelorette weekend shirts",
      "bridesmaid bachelorette shirts",
    ],
    stems: ["bachelor", "bach", "despedida", "soltera", "hen"],
    peakMonths: [],
  },
  {
    key: "bride",
    family: "Events",
    labelEn: "Brides",
    labelEs: "Novias",
    queries: [
      "bride shirt",
      "bride to be shirt",
      "future mrs shirt",
      "just married shirt",
      "honeymoon shirt",
    ],
    stems: ["bride", "novia", "wifey", "mrs", "engaged", "comprometid", "honeymoon", "married"],
    peakMonths: [],
  },
  {
    key: "wedding-party",
    family: "Events",
    labelEn: "Wedding party",
    labelEs: "Cortejo de boda",
    queries: [
      "bridesmaid shirt",
      "groomsmen shirt",
      "wedding party shirts",
      "maid of honor shirt",
      "bridal party shirts",
    ],
    stems: ["bridesmaid", "groomsm", "bridal", "wedding", "boda", "dama", "padrin", "madrin"],
    peakMonths: [],
  },
  {
    key: "graduation",
    family: "Events",
    labelEn: "Graduation",
    labelEs: "Graduación",
    queries: [
      "graduation shirt",
      "senior class shirt",
      "proud graduate family shirt",
      "grad party shirt",
      "graduation family shirts",
    ],
    stems: ["grad", "senior", "classof", "egresad", "generacion", "diploma"],
    peakMonths: [4, 5, 6],
  },
  {
    key: "back-to-school",
    family: "Events",
    labelEn: "Back to school",
    labelEs: "Regreso a clases",
    queries: [
      "back to school shirt",
      "first day of school shirt",
      "kindergarten shirt",
      "pre k shirt",
    ],
    stems: ["school", "escuela", "kinder", "preschool", "prek", "grade", "clases", "regreso"],
    peakMonths: [7, 8],
  },
  {
    key: "retirement",
    family: "Events",
    labelEn: "Retirement",
    labelEs: "Jubilación",
    queries: [
      "retirement shirt",
      "retired shirt",
      "funny retirement t-shirt",
      "retirement gift shirt",
    ],
    stems: ["retire", "jubil", "pension", "farewell"],
    peakMonths: [],
  },
  {
    key: "gender-reveal",
    family: "Events",
    labelEn: "Gender reveal",
    labelEs: "Revelación de género",
    queries: [
      "gender reveal shirt",
      "team boy shirt",
      "team girl shirt",
      "gender reveal party shirts",
    ],
    stems: ["gender", "reveal", "revela", "genero", "boyorgirl"],
    peakMonths: [],
  },
  {
    key: "vacation-group",
    family: "Events",
    labelEn: "Group trips and vacations",
    labelEs: "Viajes y vacaciones en grupo",
    queries: ["family vacation shirts", "cruise shirts", "beach vacation shirt", "road trip shirt"],
    stems: [
      "vacation",
      "vacacion",
      "cruise",
      "crucero",
      "beach",
      "playa",
      "trip",
      "viaje",
      "roadtrip",
    ],
    peakMonths: [3, 6, 7],
  },
  {
    key: "fishing",
    family: "Hobbies and sports",
    labelEn: "Fishing",
    labelEs: "Pesca",
    queries: ["fishing shirt", "funny fishing t-shirt", "bass fishing shirt", "fishing dad shirt"],
    stems: ["fish", "pesca", "angler", "bass", "trout", "reel", "lure", "bait"],
    peakMonths: [4, 5, 6],
  },
  {
    key: "hunting",
    family: "Hobbies and sports",
    labelEn: "Hunting",
    labelEs: "Cacería",
    queries: ["hunting shirt", "deer hunting shirt", "funny hunting t-shirt", "duck hunting shirt"],
    stems: ["hunt", "caza", "cacer", "deer", "venad", "buck", "duck", "camo"],
    peakMonths: [9, 10, 11],
  },
  {
    key: "camping",
    family: "Hobbies and sports",
    labelEn: "Camping",
    labelEs: "Campismo",
    queries: ["camping shirt", "funny camping t-shirt", "camp life shirt", "camping family shirts"],
    stems: ["camp", "acamp", "tent", "rv", "smore", "glamp"],
    peakMonths: [5, 6, 7],
  },
  {
    key: "hiking",
    family: "Hobbies and sports",
    labelEn: "Hiking and outdoors",
    labelEs: "Senderismo y aire libre",
    queries: ["hiking shirt", "mountain hiking t-shirt", "nature lover shirt", "adventure shirt"],
    stems: ["hike", "hiking", "trail", "mountain", "montan", "sender", "outdoor", "natur"],
    peakMonths: [],
  },
  {
    key: "gardening",
    family: "Hobbies and sports",
    labelEn: "Gardening and plants",
    labelEs: "Jardinería y plantas",
    queries: [
      "gardening shirt",
      "funny gardening t-shirt",
      "plant lady shirt",
      "plant mom shirt",
      "garden shirt",
    ],
    stems: ["garden", "jardin", "plant", "flower", "flor", "succulent", "huerto"],
    peakMonths: [3, 4, 5],
  },
  {
    key: "gaming",
    family: "Hobbies and sports",
    labelEn: "Gaming",
    labelEs: "Videojuegos",
    queries: ["gamer shirt", "funny gaming t-shirt", "video game shirt", "gaming controller shirt"],
    stems: ["gamer", "gaming", "videogame", "videojueg", "controller", "respawn", "noob"],
    peakMonths: [],
  },
  {
    key: "reading",
    family: "Hobbies and sports",
    labelEn: "Books and reading",
    labelEs: "Libros y lectura",
    queries: [
      "book lover shirt",
      "reading shirt",
      "librarian shirt",
      "bookish t-shirt",
      "book club shirt",
    ],
    stems: ["book", "reading", "reader", "libro", "lectur", "librar", "leer"],
    peakMonths: [],
  },
  {
    key: "running",
    family: "Hobbies and sports",
    labelEn: "Running",
    labelEs: "Correr",
    queries: [
      "running shirt",
      "funny running t-shirt",
      "marathon shirt",
      "5k shirt",
      "runner shirt",
    ],
    stems: ["running", "runner", "marathon", "maraton", "5k", "10k", "corredor", "correr"],
    peakMonths: [],
  },
  {
    key: "cycling",
    family: "Hobbies and sports",
    labelEn: "Cycling",
    labelEs: "Ciclismo",
    queries: ["cycling shirt", "funny cycling t-shirt", "bike shirt", "mountain bike shirt"],
    stems: ["cycling", "cyclist", "bike", "bicycle", "ciclis", "bici", "mtb"],
    peakMonths: [],
  },
  {
    key: "sports-fan-generic",
    family: "Hobbies and sports",
    labelEn: "Sports fans (no team)",
    labelEs: "Aficionados al deporte (sin equipo)",
    queries: [
      "sports fan shirt",
      "football mom shirt",
      "baseball mom shirt",
      "soccer mom shirt",
      "basketball shirt",
    ],
    stems: [
      "football",
      "futbol",
      "baseball",
      "beisbol",
      "basketball",
      "basquet",
      "soccer",
      "softball",
      "volleyball",
      "tailgat",
    ],
    peakMonths: [],
  },
  {
    key: "golf",
    family: "Hobbies and sports",
    labelEn: "Golf",
    labelEs: "Golf",
    queries: ["golf shirt", "funny golf t-shirt", "golf dad shirt", "golfer gift shirt"],
    stems: ["golf", "putt", "birdie", "fairway", "caddie"],
    peakMonths: [5, 6],
  },
  {
    key: "faith",
    family: "Faith and community",
    labelEn: "Faith",
    labelEs: "Fe",
    queries: [
      "christian shirt",
      "faith t-shirt",
      "bible verse shirt",
      "blessed shirt",
      "jesus shirt",
    ],
    stems: [
      "faith",
      "christian",
      "cristian",
      "jesus",
      "bibl",
      "bless",
      "bendecid",
      "god",
      "dios",
      "pray",
    ],
    peakMonths: [],
  },
  {
    key: "pride",
    family: "Faith and community",
    labelEn: "LGBTQ+ pride",
    labelEs: "Orgullo LGBTQ+",
    queries: [
      "pride shirt",
      "lgbtq pride shirt",
      "rainbow pride t-shirt",
      "pride month shirt",
      "ally shirt",
    ],
    stems: [
      "pride",
      "lgbt",
      "orgullo",
      "rainbow",
      "arcoiris",
      "queer",
      "gay",
      "lesbian",
      "transgender",
      "ally",
    ],
    peakMonths: [6],
  },
  {
    key: "awareness-ribbon",
    family: "Faith and community",
    labelEn: "Awareness causes",
    labelEs: "Causas y concientización",
    queries: [
      "awareness ribbon shirt",
      "breast cancer awareness shirt",
      "autism awareness shirt",
      "cancer survivor shirt",
      "mental health awareness shirt",
    ],
    stems: [
      "awareness",
      "ribbon",
      "cancer",
      "survivor",
      "sobrevivi",
      "autis",
      "concientiza",
      "lazo",
    ],
    peakMonths: [],
  },
  {
    key: "local-pride",
    family: "Faith and community",
    labelEn: "Hometown pride",
    labelEs: "Orgullo de mi tierra",
    queries: [
      "hometown shirt",
      "state pride shirt",
      "home state t-shirt",
      "city pride shirt",
      "small town shirt",
    ],
    stems: ["hometown", "homestate", "local", "smalltown", "pueblo", "tierra"],
    peakMonths: [],
  },
  {
    key: "funny-sarcastic",
    family: "Style and humor",
    labelEn: "Funny and sarcastic",
    labelEs: "Humor y sarcasmo",
    queries: [
      "funny shirt",
      "sarcastic t-shirt",
      "funny sayings shirt",
      "sarcasm shirt",
      "introvert shirt",
    ],
    stems: ["funny", "sarcas", "humor", "joke", "chiste", "gracios", "meme", "pun", "introvert"],
    peakMonths: [],
  },
  {
    key: "retro-70s",
    family: "Style and humor",
    labelEn: "Retro 70s",
    labelEs: "Retro años 70",
    queries: [
      "retro 70s shirt",
      "groovy shirt",
      "70s style t-shirt",
      "retro sunset shirt",
      "hippie shirt",
    ],
    stems: ["retro", "groovy", "70s", "seventies", "setenta", "hippie", "disco", "boho"],
    peakMonths: [],
  },
  {
    key: "vintage-distressed",
    family: "Style and humor",
    labelEn: "Vintage distressed",
    labelEs: "Vintage desgastado",
    queries: [
      "vintage distressed shirt",
      "vintage style t-shirt",
      "distressed graphic tee",
      "faded vintage shirt",
    ],
    stems: ["vintage", "distress", "faded", "grunge", "desgast", "worn", "oldschool"],
    peakMonths: [],
  },
  {
    key: "minimalist-text",
    family: "Style and humor",
    labelEn: "Minimalist text",
    labelEs: "Texto minimalista",
    queries: ["minimalist shirt", "simple text shirt", "minimalist graphic tee", "one word shirt"],
    stems: ["minimal", "simple", "text", "typograph", "tipograf", "aesthetic"],
    peakMonths: [],
  },
  {
    key: "dogs",
    family: "Animals",
    labelEn: "Dogs",
    labelEs: "Perros",
    queries: ["dog shirt", "dog lover shirt", "funny dog t-shirt", "puppy shirt"],
    stems: ["dog", "pup", "perr", "canin", "paw", "woof"],
    peakMonths: [],
  },
  {
    key: "cats",
    family: "Animals",
    labelEn: "Cats",
    labelEs: "Gatos",
    queries: [
      "cat shirt",
      "cat lover shirt",
      "funny cat t-shirt",
      "black cat shirt",
      "kitten shirt",
    ],
    stems: ["cat", "cats", "kitt", "gato", "gatit", "michi", "meow", "felin"],
    peakMonths: [],
  },
  {
    key: "horses",
    family: "Animals",
    labelEn: "Horses and rodeo",
    labelEs: "Caballos y rodeo",
    queries: [
      "horse shirt",
      "horse lover shirt",
      "equestrian shirt",
      "horse girl shirt",
      "rodeo shirt",
    ],
    stems: ["horse", "caball", "equestr", "ecuestr", "rodeo", "pony", "cowgirl", "charr"],
    peakMonths: [],
  },
];

const BY_KEY: ReadonlyMap<string, Niche> = new Map(NICHES.map((n) => [n.key, n]));

export function nicheByKey(key: string): Niche | undefined {
  return BY_KEY.get(key);
}

/** The shop-facing label; an unknown key comes back as itself. */
export function nicheLabel(key: string, lang: "en" | "es"): string {
  const n = BY_KEY.get(key);
  if (!n) return key;
  return lang === "es" ? n.labelEs : n.labelEn;
}

/** Every canonical query of the taxonomy (the only keys allowed in `market_series_cache`). */
export const CANONICAL_QUERIES: ReadonlySet<string> = new Set(NICHES.flatMap((n) => n.queries));
