/**
 * Sample class-25 trademark index for the risk check (global table, not tenant data).
 * A stand-in for the USPTO bulk build: well-known apparel/brand marks, slogans, characters and
 * a list of generic words that should never raise risk. Invented plausibly, not legal data.
 *
 * This is InvAI's versioned reference dataset (T-1-5, `REFERENCE_DATA_VERSION` in `./index.ts`),
 * not seed data: it is upserted by `ensureReferenceData` at the end of every migration run, so it
 * exists before any tenant does. B-46 (wave 8) replaces it with a real USPTO bulk loader.
 */

type Mark = {
  mark: string;
  owner: string | null;
  kind: "word" | "slogan" | "character" | "generic";
};

const BRANDS: [string, string][] = [
  ["NIKE", "Nike, Inc."],
  ["ADIDAS", "adidas AG"],
  ["PUMA", "Puma SE"],
  ["REEBOK", "Reebok International"],
  ["UNDER ARMOUR", "Under Armour, Inc."],
  ["NEW BALANCE", "New Balance Athletics"],
  ["CONVERSE", "Converse Inc."],
  ["VANS", "Vans, Inc."],
  ["CHAMPION", "HBI Branded Apparel"],
  ["HANES", "HBI Branded Apparel"],
  ["GILDAN", "Gildan Activewear"],
  ["BELLA+CANVAS", "Bella+Canvas"],
  ["COMFORT COLORS", "Comfort Colors"],
  ["CARHARTT", "Carhartt, Inc."],
  ["DICKIES", "Williamson-Dickie"],
  ["LEVI'S", "Levi Strauss & Co."],
  ["WRANGLER", "Wrangler Apparel"],
  ["LEE", "The H.D. Lee Company"],
  ["RALPH LAUREN", "PRL USA Holdings"],
  ["POLO", "PRL USA Holdings"],
  ["TOMMY HILFIGER", "Tommy Hilfiger Licensing"],
  ["CALVIN KLEIN", "Calvin Klein Trademark Trust"],
  ["GUCCI", "Guccio Gucci S.p.A."],
  ["PRADA", "Prada S.A."],
  ["LOUIS VUITTON", "Louis Vuitton Malletier"],
  ["CHANEL", "Chanel, Inc."],
  ["DIOR", "Christian Dior Couture"],
  ["VERSACE", "Gianni Versace S.r.l."],
  ["ARMANI", "GA Modefine"],
  ["BURBERRY", "Burberry Limited"],
  ["SUPREME", "Chapter 4 Corp."],
  ["OFF-WHITE", "Off-White LLC"],
  ["BAPE", "Nowhere Co."],
  ["STUSSY", "Stussy, Inc."],
  ["THE NORTH FACE", "The North Face Apparel"],
  ["PATAGONIA", "Patagonia, Inc."],
  ["COLUMBIA", "Columbia Sportswear"],
  ["ARC'TERYX", "Amer Sports"],
  ["LULULEMON", "lululemon athletica"],
  ["ATHLETA", "Gap (Apparel) LLC"],
  ["GAP", "Gap (Apparel) LLC"],
  ["OLD NAVY", "Old Navy (Apparel) LLC"],
  ["BANANA REPUBLIC", "Banana Republic (Apparel)"],
  ["AMERICAN EAGLE", "Retail Royalty Company"],
  ["AEROPOSTALE", "Aeropostale Procurement"],
  ["ABERCROMBIE", "Abercrombie & Fitch"],
  ["HOLLISTER", "Abercrombie & Fitch"],
  ["FOREVER 21", "Forever 21, Inc."],
  ["H&M", "H & M Hennes & Mauritz"],
  ["ZARA", "Industria de Diseño Textil"],
  ["UNIQLO", "Fast Retailing"],
  ["SHEIN", "Roadget Business"],
  ["URBAN OUTFITTERS", "Urban Outfitters, Inc."],
  ["FREE PEOPLE", "Urban Outfitters, Inc."],
  ["ANTHROPOLOGIE", "Urban Outfitters, Inc."],
  ["J.CREW", "J. Crew International"],
  ["MADEWELL", "J. Crew International"],
  ["EVERLANE", "Everlane, Inc."],
  ["ALLBIRDS", "Allbirds, Inc."],
  ["CROCS", "Crocs, Inc."],
  ["BIRKENSTOCK", "Birkenstock IP"],
  ["UGG", "Deckers Outdoor"],
  ["TIMBERLAND", "TBL Licensing"],
  ["DR. MARTENS", "Airwair International"],
  ["HARLEY-DAVIDSON", "H-D U.S.A., LLC"],
  ["FORD", "Ford Motor Company"],
  ["CHEVROLET", "General Motors"],
  ["JEEP", "FCA US LLC"],
  ["DODGE", "FCA US LLC"],
  ["MOPAR", "FCA US LLC"],
  ["TOYOTA", "Toyota Motor Corporation"],
  ["HONDA", "Honda Motor Co."],
  ["TESLA", "Tesla, Inc."],
  ["FERRARI", "Ferrari S.p.A."],
  ["PORSCHE", "Dr. Ing. h.c. F. Porsche AG"],
  ["BMW", "Bayerische Motoren Werke"],
  ["MERCEDES-BENZ", "Mercedes-Benz Group"],
  ["COCA-COLA", "The Coca-Cola Company"],
  ["COKE", "The Coca-Cola Company"],
  ["PEPSI", "PepsiCo, Inc."],
  ["MOUNTAIN DEW", "PepsiCo, Inc."],
  ["DR PEPPER", "Dr Pepper/Seven Up"],
  ["STARBUCKS", "Starbucks Corporation"],
  ["DUNKIN", "DD IP Holder"],
  ["MCDONALD'S", "McDonald's Corporation"],
  ["BURGER KING", "Burger King Company"],
  ["WENDY'S", "Quality Is Our Recipe"],
  ["TACO BELL", "Taco Bell Corp."],
  ["CHICK-FIL-A", "CFA Properties"],
  ["IN-N-OUT", "In-N-Out Burgers"],
  ["WHATABURGER", "Whataburger Restaurants"],
  ["BUDWEISER", "Anheuser-Busch"],
  ["BUD LIGHT", "Anheuser-Busch"],
  ["CORONA", "Cervecería Modelo"],
  ["MODELO", "Cervecería Modelo"],
  ["HEINEKEN", "Heineken Brouwerijen"],
  ["JACK DANIEL'S", "Jack Daniel's Properties"],
  ["JIM BEAM", "Jim Beam Brands"],
  ["JOSE CUERVO", "Tequila Cuervo"],
  ["PATRON", "Patrón Spirits"],
  ["RED BULL", "Red Bull GmbH"],
  ["MONSTER ENERGY", "Monster Energy Company"],
  ["GATORADE", "Stokely-Van Camp"],
  ["DISNEY", "Disney Enterprises"],
  ["MICKEY MOUSE", "Disney Enterprises"],
  ["MINNIE MOUSE", "Disney Enterprises"],
  ["PIXAR", "Disney Enterprises"],
  ["MARVEL", "Marvel Characters"],
  ["AVENGERS", "Marvel Characters"],
  ["SPIDER-MAN", "Marvel Characters"],
  ["IRON MAN", "Marvel Characters"],
  ["CAPTAIN AMERICA", "Marvel Characters"],
  ["HULK", "Marvel Characters"],
  ["THOR", "Marvel Characters"],
  ["BLACK PANTHER", "Marvel Characters"],
  ["DEADPOOL", "Marvel Characters"],
  ["X-MEN", "Marvel Characters"],
  ["WOLVERINE", "Marvel Characters"],
  ["DC COMICS", "DC Comics"],
  ["BATMAN", "DC Comics"],
  ["SUPERMAN", "DC Comics"],
  ["WONDER WOMAN", "DC Comics"],
  ["JOKER", "DC Comics"],
  ["HARRY POTTER", "Warner Bros. Entertainment"],
  ["HOGWARTS", "Warner Bros. Entertainment"],
  ["STAR WARS", "Lucasfilm Ltd."],
  ["BABY YODA", "Lucasfilm Ltd."],
  ["THE MANDALORIAN", "Lucasfilm Ltd."],
  ["DARTH VADER", "Lucasfilm Ltd."],
  ["JEDI", "Lucasfilm Ltd."],
  ["STAR TREK", "CBS Studios"],
  ["POKEMON", "Nintendo of America"],
  ["PIKACHU", "Nintendo of America"],
  ["MARIO", "Nintendo of America"],
  ["SUPER MARIO", "Nintendo of America"],
  ["ZELDA", "Nintendo of America"],
  ["NINTENDO", "Nintendo of America"],
  ["PLAYSTATION", "Sony Interactive Entertainment"],
  ["XBOX", "Microsoft Corporation"],
  ["MINECRAFT", "Microsoft Corporation"],
  ["FORTNITE", "Epic Games"],
  ["ROBLOX", "Roblox Corporation"],
  ["CALL OF DUTY", "Activision Publishing"],
  ["HALO", "Microsoft Corporation"],
  ["SONIC THE HEDGEHOG", "SEGA"],
  ["HELLO KITTY", "Sanrio Co."],
  ["SANRIO", "Sanrio Co."],
  ["PEPPA PIG", "Entertainment One"],
  ["PAW PATROL", "Spin Master"],
  ["BLUEY", "Ludo Studio"],
  ["SESAME STREET", "Sesame Workshop"],
  ["ELMO", "Sesame Workshop"],
  ["COOKIE MONSTER", "Sesame Workshop"],
  ["SPONGEBOB", "Viacom International"],
  ["NICKELODEON", "Viacom International"],
  ["TEENAGE MUTANT NINJA TURTLES", "Viacom International"],
  ["BARBIE", "Mattel, Inc."],
  ["HOT WHEELS", "Mattel, Inc."],
  ["LEGO", "LEGO Juris A/S"],
  ["NERF", "Hasbro, Inc."],
  ["TRANSFORMERS", "Hasbro, Inc."],
  ["MY LITTLE PONY", "Hasbro, Inc."],
  ["CARE BEARS", "Those Characters From Cleveland"],
  ["SNOOPY", "Peanuts Worldwide"],
  ["PEANUTS", "Peanuts Worldwide"],
  ["CHARLIE BROWN", "Peanuts Worldwide"],
  ["GARFIELD", "Paws, Inc."],
  ["LOONEY TUNES", "Warner Bros. Entertainment"],
  ["BUGS BUNNY", "Warner Bros. Entertainment"],
  ["SCOOBY-DOO", "Warner Bros. Entertainment"],
  ["TOM AND JERRY", "Warner Bros. Entertainment"],
  ["RICK AND MORTY", "Cartoon Network"],
  ["THE SIMPSONS", "Twentieth Century Fox"],
  ["FAMILY GUY", "Twentieth Century Fox"],
  ["SOUTH PARK", "Comedy Partners"],
  ["FRIENDS", "Warner Bros. Entertainment"],
  ["THE OFFICE", "Universal Television"],
  ["DUNDER MIFFLIN", "Universal Television"],
  ["STRANGER THINGS", "Netflix Studios"],
  ["SQUID GAME", "Netflix Studios"],
  ["GAME OF THRONES", "Home Box Office"],
  ["BREAKING BAD", "Sony Pictures Television"],
  ["YELLOWSTONE", "Paramount Network"],
  ["TED LASSO", "Apple Inc."],
  ["TAYLOR SWIFT", "TAS Rights Management"],
  ["SWIFTIE", "TAS Rights Management"],
  ["ERAS TOUR", "TAS Rights Management"],
  ["BEYONCE", "BGK Trademark Holdings"],
  ["DRAKE", "Aubrey Drake Graham"],
  ["BAD BUNNY", "Rimas Entertainment"],
  ["GRATEFUL DEAD", "Grateful Dead Productions"],
  ["ROLLING STONES", "Musidor B.V."],
  ["THE BEATLES", "Apple Corps"],
  ["NIRVANA", "Nirvana LLC"],
  ["METALLICA", "Metallica"],
  ["AC/DC", "Leidseplein Presse"],
  ["KISS", "Kiss Catalog"],
  ["NFL", "NFL Properties"],
  ["NBA", "NBA Properties"],
  ["MLB", "Major League Baseball Properties"],
  ["NHL", "NHL Enterprises"],
  ["NASCAR", "NASCAR, Inc."],
  ["UFC", "Zuffa, LLC"],
  ["WWE", "World Wrestling Entertainment"],
  ["FIFA", "FIFA"],
  ["OLYMPICS", "United States Olympic Committee"],
  ["SUPER BOWL", "NFL Properties"],
  ["WORLD SERIES", "Major League Baseball Properties"],
  ["MARCH MADNESS", "NCAA"],
  ["FINAL FOUR", "NCAA"],
  ["DALLAS COWBOYS", "Dallas Cowboys Football Club"],
  ["ARIZONA CARDINALS", "Arizona Cardinals Football Club"],
  ["PHOENIX SUNS", "Phoenix Suns"],
  ["LOS ANGELES LAKERS", "Los Angeles Lakers"],
  ["NEW YORK YANKEES", "New York Yankees Partnership"],
  ["CHICAGO BULLS", "Chicago Bulls"],
  ["GREEN BAY PACKERS", "Green Bay Packers"],
  ["ALABAMA CRIMSON TIDE", "University of Alabama"],
  ["OHIO STATE", "The Ohio State University"],
  ["ARIZONA STATE", "Arizona Board of Regents"],
  ["SUN DEVILS", "Arizona Board of Regents"],
  ["WILDCATS", "Arizona Board of Regents"],
  ["APPLE", "Apple Inc."],
  ["IPHONE", "Apple Inc."],
  ["GOOGLE", "Google LLC"],
  ["AMAZON", "Amazon Technologies"],
  ["MICROSOFT", "Microsoft Corporation"],
  ["FACEBOOK", "Meta Platforms"],
  ["INSTAGRAM", "Meta Platforms"],
  ["TIKTOK", "ByteDance Ltd."],
  ["SNAPCHAT", "Snap Inc."],
  ["TWITTER", "X Corp."],
  ["YOUTUBE", "Google LLC"],
  ["NETFLIX", "Netflix, Inc."],
  ["SPOTIFY", "Spotify AB"],
  ["ETSY", "Etsy, Inc."],
  ["SHOPIFY", "Shopify Inc."],
  ["WALMART", "Walmart Apollo"],
  ["TARGET", "Target Brands"],
  ["COSTCO", "Costco Wholesale"],
  ["KIRKLAND", "Costco Wholesale"],
  ["HOME DEPOT", "Homer TLC"],
  ["LOWE'S", "LF, LLC"],
  ["JOHN DEERE", "Deere & Company"],
  ["CATERPILLAR", "Caterpillar Inc."],
  ["STANLEY", "Stanley Black & Decker"],
  ["YETI", "YETI Coolers"],
  ["REALTREE", "Jordan Outdoor Enterprises"],
  ["MOSSY OAK", "Haas Outdoors"],
  ["BASS PRO SHOPS", "Bass Pro Intellectual Property"],
  ["CABELA'S", "Cabela's LLC"],
  ["BROWNING", "Browning"],
  ["REMINGTON", "Remington Arms"],
  ["GLOCK", "Glock, Inc."],
  ["SMITH & WESSON", "Smith & Wesson Brands"],
  ["FENDER", "Fender Musical Instruments"],
  ["GIBSON", "Gibson Brands"],
  ["HARVARD", "President and Fellows of Harvard College"],
  ["YALE", "Yale University"],
  ["STANFORD", "Stanford University"],
  ["NASA", "National Aeronautics and Space Administration"],
  ["ROUTE 66", "Route 66 Association"],
  ["CROSSFIT", "CrossFit, LLC"],
  ["PELOTON", "Peloton Interactive"],
  ["JEEP WRANGLER", "FCA US LLC"],
  ["RAPTOR", "Ford Motor Company"],
  ["MUSTANG", "Ford Motor Company"],
  ["CAMARO", "General Motors"],
  ["CORVETTE", "General Motors"],
  ["SILVERADO", "General Motors"],
  ["BRONCO", "Ford Motor Company"],
  ["F-150", "Ford Motor Company"],
  ["POWER STROKE", "Ford Motor Company"],
  ["DURAMAX", "General Motors"],
  ["CUMMINS", "Cummins Inc."],
  ["HEMI", "FCA US LLC"],
  ["POLARIS", "Polaris Industries"],
  ["CAN-AM", "Bombardier Recreational Products"],
  ["KAWASAKI", "Kawasaki Motors"],
  ["YAMAHA", "Yamaha Motor Co."],
  ["DUCATI", "Ducati Motor Holding"],
  ["INDIAN MOTORCYCLE", "Indian Motorcycle International"],
  ["JORDAN", "Nike, Inc."],
  ["AIR JORDAN", "Nike, Inc."],
  ["JUMPMAN", "Nike, Inc."],
  ["SWOOSH", "Nike, Inc."],
  ["TRIPLE STRIPE", "adidas AG"],
  ["THREE STRIPES", "adidas AG"],
  ["OAKLEY", "Oakley, Inc."],
  ["RAY-BAN", "Luxottica Group"],
  ["FOSSIL", "Fossil Group"],
  ["ROLEX", "Rolex SA"],
  ["PANDORA", "Pandora A/S"],
  ["TIFFANY", "Tiffany and Company"],
  ["VICTORIA'S SECRET", "Victoria's Secret Stores Brand Management"],
  ["PINK", "Victoria's Secret Stores Brand Management"],
  ["SKIMS", "Skims Body, Inc."],
  ["FASHION NOVA", "Fashion Nova, LLC"],
  ["GYMSHARK", "Gymshark Limited"],
  ["ALO", "Color Image Apparel"],
  ["FABLETICS", "Fabletics, LLC"],
];

const SLOGANS: [string, string][] = [
  ["JUST DO IT", "Nike, Inc."],
  ["IMPOSSIBLE IS NOTHING", "adidas AG"],
  ["I'M LOVIN' IT", "McDonald's Corporation"],
  ["HAVE IT YOUR WAY", "Burger King Company"],
  ["EAT MOR CHIKIN", "CFA Properties"],
  ["LIVE MAS", "Taco Bell Corp."],
  ["THE HAPPIEST PLACE ON EARTH", "Disney Enterprises"],
  ["MAY THE FORCE BE WITH YOU", "Lucasfilm Ltd."],
  ["THIS IS THE WAY", "Lucasfilm Ltd."],
  ["I AM GROOT", "Marvel Characters"],
  ["WAKANDA FOREVER", "Marvel Characters"],
  ["GOTTA CATCH 'EM ALL", "Nintendo of America"],
  ["IT'S-A ME, MARIO", "Nintendo of America"],
  ["WHAT'S IN YOUR WALLET", "Capital One"],
  ["BECAUSE YOU'RE WORTH IT", "L'Oréal"],
  ["MELTS IN YOUR MOUTH, NOT IN YOUR HANDS", "Mars, Inc."],
  ["TASTE THE RAINBOW", "Wm. Wrigley Jr. Company"],
  ["RED BULL GIVES YOU WINGS", "Red Bull GmbH"],
  ["THE ULTIMATE DRIVING MACHINE", "Bayerische Motoren Werke"],
  ["BUILT FORD TOUGH", "Ford Motor Company"],
  ["LIKE A ROCK", "General Motors"],
  ["LET'S GO PLACES", "Toyota Motor Corporation"],
  ["THINK DIFFERENT", "Apple Inc."],
  ["SNAP CRACKLE POP", "Kellogg Company"],
  ["THEY'RE GR-R-REAT", "Kellogg Company"],
  ["BREAKFAST OF CHAMPIONS", "General Mills"],
  ["FINGER LICKIN' GOOD", "KFC Corporation"],
  ["AMERICA RUNS ON DUNKIN", "DD IP Holder"],
  ["WHAT HAPPENS HERE, STAYS HERE", "Las Vegas Convention and Visitors Authority"],
  ["VIRGINIA IS FOR LOVERS", "Virginia Tourism Corporation"],
  ["I LOVE NY", "New York State Department of Economic Development"],
  ["KEEP AUSTIN WEIRD", "Outhouse Designs"],
  ["DON'T MESS WITH TEXAS", "Texas Department of Transportation"],
  ["LIFE IS GOOD", "The Life is Good Company"],
  ["SALT LIFE", "Salt Life, LLC"],
  ["NO FEAR", "No Fear, Inc."],
  ["LET'S GO BRANDON", "Various applicants"],
  ["GIRL BOSS", "Girlboss Media"],
  ["THAT'S HOT", "Paris Hilton Entertainment"],
  ["HAKUNA MATATA", "Disney Enterprises"],
  ["TO INFINITY AND BEYOND", "Disney Enterprises"],
  ["LET IT GO", "Disney Enterprises"],
  ["I'LL BE BACK", "StudioCanal"],
  ["MAY THE ODDS BE EVER IN YOUR FAVOR", "Lions Gate Films"],
  ["WINTER IS COMING", "Home Box Office"],
  ["WE'RE ALL MAD HERE", "Disney Enterprises"],
  ["BOO-YAH", "ESPN"],
  ["LET'S GET READY TO RUMBLE", "Michael Buffer"],
  ["ARE YOU READY FOR SOME FOOTBALL", "NFL Properties"],
  ["THE BIG GAME", "NFL Properties"],
  ["MARCH MADNESS", "NCAA"],
  ["BAMA", "University of Alabama"],
  ["FEAR THE FORK", "Arizona Board of Regents"],
  ["BEAR DOWN", "Arizona Board of Regents"],
  ["ROLL TIDE", "University of Alabama"],
  ["HOOK 'EM HORNS", "University of Texas"],
  ["GO BLUE", "University of Michigan"],
  ["WAR EAGLE", "Auburn University"],
];

const CHARACTERS: [string, string][] = [
  ["GROOT", "Marvel Characters"],
  ["GROGU", "Lucasfilm Ltd."],
  ["YODA", "Lucasfilm Ltd."],
  ["CHEWBACCA", "Lucasfilm Ltd."],
  ["STITCH", "Disney Enterprises"],
  ["ELSA", "Disney Enterprises"],
  ["MOANA", "Disney Enterprises"],
  ["SIMBA", "Disney Enterprises"],
  ["WINNIE THE POOH", "Disney Enterprises"],
  ["TIGGER", "Disney Enterprises"],
  ["BUZZ LIGHTYEAR", "Disney Enterprises"],
  ["WOODY", "Disney Enterprises"],
  ["LIGHTNING MCQUEEN", "Disney Enterprises"],
  ["MINIONS", "Universal City Studios"],
  ["GRU", "Universal City Studios"],
  ["SHREK", "DreamWorks Animation"],
  ["KUNG FU PANDA", "DreamWorks Animation"],
  ["HOMER SIMPSON", "Twentieth Century Fox"],
  ["BART SIMPSON", "Twentieth Century Fox"],
  ["SQUIDWARD", "Viacom International"],
  ["PATRICK STAR", "Viacom International"],
  ["ELEVEN", "Netflix Studios"],
  ["DEMOGORGON", "Netflix Studios"],
  ["MICHAEL MYERS", "Compass International Pictures"],
  ["FREDDY KRUEGER", "New Line Productions"],
  ["JASON VOORHEES", "Horror, Inc."],
  ["CHUCKY", "Universal City Studios"],
  ["GHOSTFACE", "Fun World"],
  ["SPIDER-GWEN", "Marvel Characters"],
  ["MILES MORALES", "Marvel Characters"],
];

/** Everyday words that appear in real marks but should never raise a risk on their own. */
const GENERIC = [
  "sun",
  "desert",
  "cactus",
  "saguaro",
  "bloom",
  "flower",
  "mountain",
  "wave",
  "ocean",
  "beach",
  "coffee",
  "mama",
  "mom",
  "dad",
  "papa",
  "grandma",
  "nana",
  "bride",
  "bachelorette",
  "birthday",
  "christmas",
  "halloween",
  "easter",
  "thanksgiving",
  "fourth of july",
  "teacher",
  "nurse",
  "coach",
  "camping",
  "hiking",
  "fishing",
  "hunting",
  "golf",
  "baseball",
  "softball",
  "football",
  "soccer",
  "dance",
  "cheer",
  "dog",
  "cat",
  "horse",
  "retro",
  "vintage",
  "boho",
  "western",
  "cowgirl",
  "cowboy",
  "rodeo",
  "wild",
  "free",
  "blessed",
  "grateful",
  "faith",
  "vibes",
  "summer",
  "fall",
  "autumn",
  "winter",
  "spring",
  "pumpkin",
  "spooky",
  "custom",
  "personalized",
  "family",
  "reunion",
  "vacation",
  "trip",
  "class of",
  "senior",
  "graduate",
  "wedding",
  "anniversary",
  "arizona",
  "phoenix",
  "tucson",
  "sedona",
  "texas",
  "california",
  "florida",
  "nashville",
  "vegas",
];

export function normalizeMark(text: string): string {
  return text
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export const TRADEMARK_MARKS: Mark[] = [
  ...BRANDS.map(([mark, owner]) => ({ mark, owner, kind: "word" as const })),
  ...SLOGANS.map(([mark, owner]) => ({ mark, owner, kind: "slogan" as const })),
  ...CHARACTERS.map(([mark, owner]) => ({ mark, owner, kind: "character" as const })),
  ...GENERIC.map((mark) => ({ mark, owner: null, kind: "generic" as const })),
];
